// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mzwftacoaxuakfjlmwti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16d2Z0YWNvYXh1YWtmamxtd3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTAxNzMsImV4cCI6MjA3MDM2NjE3M30.TjRhwpowSBQ1hmPFPD8wv1tfM1Kuk09wCN9p2QIWeUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);